# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-28 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[(b'server', b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (b'other', b'\xe5\x85\xb6\xe4\xbb\x96')], default=b'server', max_length=64, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe5\x90\x8d\xe7\xa7\xb0')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('status', models.SmallIntegerField(choices=[(0, b'\xe5\x9c\xa8\xe7\xba\xbf'), (1, b'\xe4\xb8\x8b\xe7\xba\xbf'), (2, b'\xe6\x9c\xaa\xe7\x9f\xa5'), (3, b'\xe6\x95\x85\xe9\x9a\x9c'), (4, b'\xe5\x85\xa5\xe5\xba\x93')], default=0, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\x8a\xb6\xe6\x80\x81')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86IP')),
                ('purchase_day', models.DateField(blank=True, null=True, verbose_name=b'\xe8\xb4\xad\xe4\xb9\xb0\xe6\x97\xb6\xe6\x9c\x9f')),
                ('expire_day', models.DateField(blank=True, null=True, verbose_name=b'\xe8\xbf\x87\xe4\xbf\x9d\xe6\x97\xa5\xe6\x9c\x9f')),
                ('price', models.FloatField(blank=True, null=True, verbose_name=b'\xe4\xbb\xb7\xe6\xa0\xbc')),
                ('memo', models.TextField(blank=True, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x89\xb9\xe5\x87\x86\xe6\x97\xa5\xe6\x9c\x9f')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x89\xb9\xe5\x87\x86\xe4\xba\xba')),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name': '\u8d44\u4ea7\u603b\u8868',
                'verbose_name_plural': '\u8d44\u4ea7\u603b\u8868',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xba\xbf')),
                ('memo', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_level', to='devops.BusinessUnit')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1\u7ebf',
                'verbose_name_plural': '\u4e1a\u52a1\u7ebf',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name=b'\xe5\x90\x88\xe5\x90\x8c\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=64, verbose_name=b'\xe5\x90\x88\xe5\x90\x8c\xe5\x90\x8d\xe7\xa7\xb0')),
                ('memo', models.TextField(blank=True, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('price', models.IntegerField(verbose_name=b'\xe5\x90\x88\xe5\x90\x8c\xe9\x87\x91\xe9\xa2\x9d')),
                ('detail', models.TextField(blank=True, null=True, verbose_name=b'\xe5\x90\x88\xe5\x90\x8c\xe8\xaf\xa6\xe7\xbb\x86')),
                ('start_day', models.DateField(blank=True, null=True, verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xa5\xe6\x9c\x9f')),
                ('end_day', models.DateField(blank=True, null=True, verbose_name=b'\xe5\xa4\xb1\xe6\x95\x88\xe6\x97\xa5\xe6\x9c\x9f')),
                ('license_num', models.IntegerField(blank=True, null=True, verbose_name=b'license\xe6\x95\xb0\xe9\x87\x8f')),
                ('c_day', models.DateField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xa5\xe6\x9c\x9f')),
                ('m_day', models.DateField(auto_now=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'verbose_name': '\u5408\u540c',
                'verbose_name_plural': '\u5408\u540c',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'CPU\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('cpu_count', models.PositiveSmallIntegerField(default=1, verbose_name=b'\xe7\x89\xa9\xe7\x90\x86CPU\xe4\xb8\xaa\xe6\x95\xb0')),
                ('cpu_core_count', models.PositiveSmallIntegerField(default=1, verbose_name=b'CPU\xe6\xa0\xb8\xe6\x95\xb0')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devops.Asset')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPU',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, verbose_name=b'\xe7\xa1\xac\xe7\x9b\x98SN\xe5\x8f\xb7')),
                ('slot', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe6\x89\x80\xe5\x9c\xa8\xe6\x8f\x92\xe6\xa7\xbd\xe4\xbd\x8d')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe7\xa3\x81\xe7\x9b\x98\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe7\xa3\x81\xe7\x9b\x98\xe5\x88\xb6\xe9\x80\xa0\xe5\x95\x86')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name=b'\xe7\xa3\x81\xe7\x9b\x98\xe5\xae\xb9\xe9\x87\x8f(GB)')),
                ('interface_type', models.CharField(choices=[(b'SATA', b'SATA'), (b'SAS', b'SAS'), (b'SCSI', b'SCSI'), (b'SSD', b'SSD'), (b'unknown', b'unknown')], default=b'unknown', max_length=16, verbose_name=b'\xe6\x8e\xa5\xe5\x8f\xa3\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Asset')),
            ],
            options={
                'verbose_name': '\u786c\u76d8',
                'verbose_name_plural': '\u786c\u76d8',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'\xe4\xba\x8b\xe4\xbb\xb6\xe5\x90\x8d\xe7\xa7\xb0')),
                ('event_type', models.SmallIntegerField(choices=[(0, b'\xe5\x85\xb6\xe5\xae\x83'), (1, b'\xe7\xa1\xac\xe4\xbb\xb6\xe5\x8f\x98\xe6\x9b\xb4'), (2, b'\xe6\x96\xb0\xe5\xa2\x9e\xe9\x85\x8d\xe4\xbb\xb6'), (3, b'\xe8\xae\xbe\xe5\xa4\x87\xe4\xb8\x8b\xe7\xba\xbf'), (4, b'\xe8\xae\xbe\xe5\xa4\x87\xe4\xb8\x8a\xe7\xba\xbf'), (5, b'\xe5\xae\x9a\xe6\x9c\x9f\xe7\xbb\xb4\xe6\x8a\xa4'), (6, b'\xe4\xb8\x9a\xe5\x8a\xa1\xe4\xb8\x8a\xe7\xba\xbf\\\xe6\x9b\xb4\xe6\x96\xb0\\\xe5\x8f\x98\xe6\x9b\xb4')], default=4, verbose_name=b'\xe4\xba\x8b\xe4\xbb\xb6\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('component', models.CharField(blank=True, max_length=256, null=True, verbose_name=b'\xe4\xba\x8b\xe4\xbb\xb6\xe5\xad\x90\xe9\xa1\xb9')),
                ('detail', models.TextField(verbose_name=b'\xe4\xba\x8b\xe4\xbb\xb6\xe8\xaf\xa6\xe6\x83\x85')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe4\xba\x8b\xe4\xbb\xb6\xe6\x97\xb6\xe9\x97\xb4')),
                ('memo', models.TextField(blank=True, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.Asset')),
            ],
            options={
                'verbose_name': '\u4e8b\u4ef6\u7eaa\u5f55',
                'verbose_name_plural': '\u4e8b\u4ef6\u7eaa\u5f55',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf\xe5\x90\x8d\xe7\xa7\xb0')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'\xe5\x8e\x82\xe5\x95\x86\xe5\x90\x8d\xe7\xa7\xb0')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x8c\x81\xe7\x94\xb5\xe8\xaf\x9d')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
            options={
                'verbose_name': '\u5382\u5546',
                'verbose_name_plural': '\u5382\u5546',
            },
        ),
        migrations.CreateModel(
            name='MonitorServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, null=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name=b'\xe8\xa2\xab\xe7\x9b\x91\xe6\x8e\xa7\xe8\x8a\x82\xe7\x82\xb9IP')),
                ('now_time', models.CharField(max_length=64)),
                ('cpu_util', models.CharField(max_length=16, verbose_name=b'CPU\xe5\x88\xa9\xe7\x94\xa8\xe7\x8e\x87')),
                ('free_mem', models.CharField(max_length=16, verbose_name=b'\xe7\xa9\xba\xe9\x97\xb2\xe5\x86\x85\xe5\xad\x98\xe6\xaf\x94\xe4\xbe\x8b')),
                ('disk_usage', models.CharField(max_length=16, verbose_name=b'\xe7\xa3\x81\xe7\x9b\x98\xe7\xa9\xba\xe9\x97\xb2\xe5\x88\xa9\xe7\x94\xa8\xe7\x8e\x87')),
                ('nic_rx', models.CharField(max_length=16, verbose_name=b'\xe6\x8e\xa5\xe6\x94\xb6\xe4\xb8\xa2\xe5\x8c\x85\xe7\x8e\x87')),
                ('nic_tx', models.CharField(max_length=16, verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe4\xb8\xa2\xe5\x8c\x85\xe7\x8e\x87')),
                ('memo', models.TextField(blank=True, db_column=b'\xe5\xa4\x87\xe6\xb3\xa8', default=b'\xe6\x97\xa0', null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='NewAssetApprovalZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7SN\xe5\x8f\xb7')),
                ('asset_type', models.CharField(blank=True, choices=[(b'server', b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (b'networkdevice', b'\xe7\xbd\x91\xe7\xbb\x9c\xe8\xae\xbe\xe5\xa4\x87'), (b'storagedevice', b'\xe5\xad\x98\xe5\x82\xa8\xe8\xae\xbe\xe5\xa4\x87'), (b'securitydevice', b'\xe5\xae\x89\xe5\x85\xa8\xe8\xae\xbe\xe5\xa4\x87'), (b'IDC', b'\xe6\x9c\xba\xe6\x88\xbf'), (b'software', b'\xe8\xbd\xaf\xe4\xbb\xb6\xe8\xb5\x84\xe4\xba\xa7')], default=b'server', max_length=64, null=True, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe7\x94\x9f\xe4\xba\xa7\xe5\x8e\x82\xe5\x95\x86')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('ram_size', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\xa4\xa7\xe5\xb0\x8f')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'CPU\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('cpu_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cpu_core_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('os_distribution', models.CharField(blank=True, max_length=64, null=True)),
                ('os_type', models.CharField(blank=True, max_length=64, null=True)),
                ('os_release', models.CharField(blank=True, max_length=64, null=True)),
                ('data', models.TextField(verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe6\x95\xb0\xe6\x8d\xae')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb1\x87\xe6\x8a\xa5\xe6\x97\xa5\xe6\x9c\x9f')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
                ('approved', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x89\xb9\xe5\x87\x86')),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name': '\u65b0\u4e0a\u7ebf\u5f85\u6279\u51c6\u8d44\u4ea7',
                'verbose_name_plural': '\u65b0\u4e0a\u7ebf\u5f85\u6279\u51c6\u8d44\u4ea7',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe7\xbd\x91\xe5\x8d\xa1\xe5\x90\x8d\xe7\xa7\xb0')),
                ('model', models.CharField(max_length=128, verbose_name=b'\xe7\xbd\x91\xe5\x8d\xa1\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('mac', models.CharField(max_length=64, verbose_name=b'MAC\xe5\x9c\xb0\xe5\x9d\x80')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name=b'IP\xe5\x9c\xb0\xe5\x9d\x80')),
                ('net_mask', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe6\x8e\xa9\xe7\xa0\x81')),
                ('bonding', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe7\xbb\x91\xe5\xae\x9a\xe5\x9c\xb0\xe5\x9d\x80')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Asset')),
            ],
            options={
                'verbose_name': '\u7f51\u5361',
                'verbose_name_plural': '\u7f51\u5361',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'SN\xe5\x8f\xb7')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\x88\xb6\xe9\x80\xa0\xe5\x95\x86')),
                ('slot', models.CharField(max_length=64, verbose_name=b'\xe6\x8f\x92\xe6\xa7\xbd')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\xa4\xa7\xe5\xb0\x8f(GB)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Asset')),
            ],
            options={
                'verbose_name': '\u5185\u5b58',
                'verbose_name_plural': '\u5185\u5b58',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_asset_type', models.SmallIntegerField(choices=[(0, b'PC\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (1, b'\xe5\x88\x80\xe7\x89\x87\xe6\x9c\xba'), (2, b'\xe5\xb0\x8f\xe5\x9e\x8b\xe6\x9c\xba')], default=0, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('created_by', models.CharField(choices=[(b'auto', b'\xe8\x87\xaa\xe5\x8a\xa8\xe6\xb7\xbb\xe5\x8a\xa0'), (b'manual', b'\xe6\x89\x8b\xe5\xb7\xa5\xe5\xbd\x95\xe5\x85\xa5')], default=b'auto', max_length=32, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x96\xb9\xe5\xbc\x8f')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('raid_type', models.CharField(blank=True, max_length=512, null=True, verbose_name=b'Raid\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('os_type', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('os_distribution', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\x8f\x91\xe8\xa1\x8c\xe7\x89\x88\xe6\x9c\xac')),
                ('os_release', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x89\x88\xe6\x9c\xac')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devops.Asset')),
                ('hosted_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_on_server', to='devops.Server', verbose_name=b'\xe5\xae\xbf\xe4\xb8\xbb\xe6\x9c\xba')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668',
                'verbose_name_plural': '\u670d\u52a1\u5668',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, null=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('service_name', models.CharField(max_length=32, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x90\x8d\xe7\xa7\xb0')),
                ('service_status', models.SmallIntegerField(choices=[(0, b'down'), (1, b'active')], default=1, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe7\x8a\xb6\xe6\x80\x81')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe5\x90\x8d')),
                ('c_day', models.DateField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='eventlog',
            name='new_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.NewAssetApprovalZone'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xba\x8b\xe4\xbb\xb6\xe6\x89\xa7\xe8\xa1\x8c\xe4\xba\xba'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bussiness_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.BusinessUnit', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xb3\xbb\xe7\xbb\x9f'),
        ),
        migrations.AddField(
            model_name='asset',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Contract', verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.IDC', verbose_name=b'\xe6\x89\x80\xe5\x9c\xa8\xe6\x9c\xba\xe6\x88\xbf'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Manufacturer', verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe5\x88\xb6\xe9\x80\xa0\xe5\x95\x86'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='devops.Tag', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe'),
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([('asset', 'slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together=set([('asset', 'model', 'mac')]),
        ),
        migrations.AlterUniqueTogether(
            name='disk',
            unique_together=set([('asset', 'sn')]),
        ),
    ]
