# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0003_auto_20180529_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbserver',
            name='hostname',
            field=models.CharField(blank=True, db_column=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d', max_length=64, null=True, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='cmdbserver',
            name='mem_size',
            field=models.FloatField(blank=True, db_column=b'\xe5\x86\x85\xe5\xad\x98(GB)', null=True, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\xa4\xa7\xe5\xb0\x8f(GB)'),
        ),
        migrations.AlterField(
            model_name='cmdbserver',
            name='sn',
            field=models.CharField(db_column=b'\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7', max_length=128, unique=True, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7'),
        ),
    ]
