# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0004_auto_20180530_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='bussiness_unit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='parent_unit',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='disk',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='disk',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='new_asset',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='nic',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ram',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='server',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='server',
            name='hosted_on',
        ),
        migrations.RenameField(
            model_name='monitorserver',
            old_name='now_time',
            new_name='boot_time',
        ),
        migrations.RemoveField(
            model_name='monitorserver',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='monitorserver',
            name='free_mem',
        ),
        migrations.RemoveField(
            model_name='monitorserver',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='monitorserver',
            name='nic_rx',
        ),
        migrations.RemoveField(
            model_name='monitorserver',
            name='nic_tx',
        ),
        migrations.AddField(
            model_name='cmdbserver',
            name='manufacturer',
            field=models.CharField(db_column=b'\xe4\xba\xa7\xe5\x95\x86', max_length=64, null=True, verbose_name=b'\xe4\xba\xa7\xe5\x95\x86'),
        ),
        migrations.AddField(
            model_name='cmdbserver',
            name='product_model',
            field=models.CharField(db_column=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe5\x9e\x8b\xe5\x8f\xb7', max_length=64, null=True, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe5\x9e\x8b\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='average_iops',
            field=models.IntegerField(blank=True, db_column=b'IOPS', default=0, null=True),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='average_load',
            field=models.FloatField(db_column=b'\xe5\xb9\xb3\xe5\x9d\x87\xe8\xb4\x9f\xe8\xbd\xbd', default=0),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='disk_util',
            field=models.FloatField(db_column=b'\xe7\xa3\x81\xe7\x9b\x98\xe7\xa9\xba\xe9\x97\xb2\xe5\x88\xa9\xe7\x94\xa8\xe7\x8e\x87', default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='hostname',
            field=models.CharField(blank=True, db_column=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d', max_length=64, null=True, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d'),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='io_read_throughput',
            field=models.IntegerField(db_column=b'IO\xe8\xaf\xbb\xe5\x90\x9e\xe5\x90\x90\xe9\x87\x8f', default=0),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='io_write_throughput',
            field=models.IntegerField(db_column=b'IO\xe5\x86\x99\xe5\x90\x9e\xe5\x90\x90\xe9\x87\x8f', default=0),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='mem_util',
            field=models.FloatField(db_column=b'\xe5\xb7\xb2\xe7\x94\xa8\xe5\x86\x85\xe5\xad\x98\xe6\xaf\x94\xe4\xbe\x8b', default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='net_avarage_error',
            field=models.IntegerField(db_column=b'\xe6\x94\xb6\xe5\x8f\x91\xe4\xb8\xa2\xe5\x8c\x85\xe4\xb8\xaa\xe6\x95\xb0', default=0),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='nic_average_throughput',
            field=models.IntegerField(db_column=b'\xe7\xbd\x91\xe7\xbb\x9c\xe6\x94\xb6\xe5\x8f\x91\xe5\x90\x9e\xe5\x90\x90\xe9\x87\x8f', default=0),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='swap_util',
            field=models.FloatField(db_column=b'swap\xe5\x88\xa9\xe7\x94\xa8\xe7\x8e\x87', default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='monitorserver',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monitorserver',
            name='cpu_util',
            field=models.FloatField(db_column=b'CPU\xe5\x88\xa9\xe7\x94\xa8\xe7\x8e\x87', default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='monitorserver',
            name='ip',
            field=models.GenericIPAddressField(db_column=b'\xe8\xa2\xab\xe7\x9b\x91\xe6\x8e\xa7\xe8\x8a\x82\xe7\x82\xb9IP', unique=True),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='NewAssetApprovalZone',
        ),
        migrations.DeleteModel(
            name='NIC',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
