# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0005_auto_20180605_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorserver',
            old_name='net_avarage_error',
            new_name='net_average_error',
        ),
    ]
