# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0006_auto_20180605_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sender', models.EmailField(db_column=b'\xe5\x8f\x91\xe4\xbb\xb6\xe4\xba\xba\xe9\x82\xae\xe7\xae\xb1', max_length=254)),
                ('email_sender_password', models.CharField(db_column=b'\xe5\x8f\x91\xe4\xbb\xb6\xe4\xba\xba\xe5\xaf\x86\xe7\xa0\x81', max_length=16)),
                ('email_receiver', models.EmailField(db_column=b'\xe6\x8e\xa5\xe6\x94\xb6\xe4\xba\xba\xe9\x82\xae\xe7\xae\xb1', max_length=254)),
                ('email_smtp_server', models.CharField(db_column=b'SMTP\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8', max_length=64)),
                ('dingding_url', models.CharField(blank=True, db_column=b'\xe9\x92\x89\xe9\x92\x89URL\xe5\x9c\xb0\xe5\x9d\x80', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(db_column=b'\xe7\x9b\x91\xe6\x8e\xa7\xe6\xa8\xa1\xe6\x9d\xbf', default=b'common', max_length=32, unique=True)),
                ('cpu_threshold_warning', models.IntegerField()),
                ('mem_threshold_warning', models.IntegerField()),
                ('disk_threshold_warning', models.IntegerField()),
                ('swap_threshold_warning', models.IntegerField()),
                ('upload_threshold_warning', models.FloatField()),
                ('errror_packet_threhold_warning', models.IntegerField()),
                ('cpu_threshold_disaster', models.IntegerField()),
                ('mem_threshold_disaster', models.IntegerField()),
                ('disk_threshold_disaster', models.IntegerField()),
                ('swap_threshold_disaster', models.IntegerField()),
                ('upload_threshold_disaster', models.FloatField()),
                ('errror_packet_threhold_disaster', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonitorAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, b'info'), (2, b'warning'), (3, b'disaster')], db_column=b'\xe7\x9b\x91\xe6\x8e\xa7\xe7\xba\xa7\xe5\x88\xab', default=1)),
                ('time', models.DateField(auto_now=True, db_column=b'\xe5\x91\x8a\xe8\xad\xa6\xe6\x97\xb6\xe9\x97\xb4')),
                ('info', models.CharField(db_column=b'\xe5\x91\x8a\xe8\xad\xa6\xe8\xaf\xa6\xe7\xbb\x86\xe4\xbf\xa1\xe6\x81\xaf', default=b'\xe6\x97\xa0', max_length=128)),
                ('host', models.CharField(max_length=64)),
                ('ack', models.SmallIntegerField(choices=[(0, b'\xe6\x9c\xaa\xe7\xa1\xae\xe8\xae\xa4'), (1, b'\xe5\xb7\xb2\xe7\xa1\xae\xe8\xae\xa4')], db_column=b'\xe7\xa1\xae\xe8\xae\xa4\xe7\x8a\xb6\xe6\x80\x81', default=0)),
                ('item', models.ManyToManyField(db_column=b'\xe7\x9b\x91\xe6\x8e\xa7\xe9\xa1\xb9', to='devops.MonitorServer')),
            ],
        ),
    ]
