# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0007_alertconfig_alertthreshold_monitoralert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoralert',
            name='host',
            field=models.CharField(db_column=b'\xe8\xa2\xab\xe7\x9b\x91\xe6\x8e\xa7\xe8\x8a\x82\xe7\x82\xb9', max_length=64),
        ),
        migrations.RemoveField(
            model_name='monitoralert',
            name='item',
        ),
        migrations.AddField(
            model_name='monitoralert',
            name='item',
            field=models.CharField(db_column=b'\xe7\x9b\x91\xe6\x8e\xa7\xe9\xa1\xb9', max_length=64, null=True),
        ),
    ]
