# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0008_auto_20180611_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoralert',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='monitoralert',
            name='time',
            field=models.DateTimeField(auto_now=True, db_column=b'\xe5\x91\x8a\xe8\xad\xa6\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
