# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0009_auto_20180611_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorserver',
            name='net_average_error',
            field=models.FloatField(db_column=b'\xe6\x94\xb6\xe5\x8f\x91\xe4\xb8\xa2\xe5\x8c\x85\xe4\xb8\xaa\xe6\x95\xb0', default=0),
        ),
    ]
