# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0010_auto_20180612_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorserver',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
