# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0011_auto_20180613_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logpath', models.CharField(db_column=b'\xe6\x97\xa5\xe5\xbf\x97\xe8\xb7\xaf\xe5\xbe\x84', max_length=256)),
                ('name', models.CharField(db_column=b'\xe6\x98\xbe\xe7\xa4\xba\xe5\x90\x8d\xe7\xa7\xb0', max_length=32)),
            ],
        ),
    ]
